dist: trusty

language: node_js
node_js:
    - "node"

install:
    - npm install
    - npm install -g snyk

script:
    - snyk test
    - npm run lint
    - npm run test

cache:
    directories:
        - node_modules
